/* eslint-disable react/no-children-prop */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Layout from './lib/layout/layout'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'رایکن',
  description: 'Generated by create rina',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang="en" id="root">
      <body>
          {modal}
          <Layout>{children}</Layout>
      </body>
    </html>
  )
}
